### ISSUE TITLE
When the start time is in 5-minute increments, a 5-minute gap occurs in the central time.

### ISSUE THREAD

**Issue by HongEuiChan** [a1573595/ClockSlider#1]
When the start time is in 5-minute increments, a 5-minute gap occurs in the central time.

For example, set the start time to 21:35
If you set the end time to 07:20
The time displayed in the center is marked as 09:40.
Actually, it is 09:45.

Which part do I need to fix?

**Comment by a1573595** [comment]
> When the start time is in 5-minute increments, a 5-minute gap occurs in the central time.
> 
> For example, set the start time to 21:35 If you set the end time to 07:20 The time displayed in the center is marked as 09:40. Actually, it is 09:45.
> 
> Which part do I need to fix?

It's a floating point carry problem, maybe I can fix it over the weekend

**Comment by a1573595** [comment]
Fix in 1.0.1

**Comment by HongEuiChan** [comment]
Thank you for responding quickly.
Have a good time

2023년 3월 31일 (금) 오후 4:14, Chien ***@***.***>님이 작성:
